name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'chkp-gcp-prd-kenobi-box'  # Updated project ID
  REGION: 'us-west2'                     # Updated region
  SERVICE: 'thunderservice'              # Updated service name

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Authenticate with Google Cloud using Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/950783879036/locations/global/workloadIdentityPools/github/providers/my-repo'  # Replace with your pool/provider details
          service_account: 'my-service-account@chkp-gcp-prd-kenobi-box.iam.gserviceaccount.com'  # Replace with your service account

      # Deploy to Cloud Run
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'

      # Output the Cloud Run service URL
      - name: 'Show output'
        run: |-
          echo "Service URL: ${{ steps.deploy.outputs.url }}"
