name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'chkp-gcp-prd-kenobi-box'
  REGION: 'us-west2'
  SERVICE: 'thunderservice'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/950783879036/locations/global/workloadIdentityPools/github/providers/for-cloud-run'
          service_account: '950783879036-compute@chkp-gcp-prd-kenobi-box.iam.gserviceaccount.com'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'
          allow_unauthenticated: true

      - name: 'Show output'
        run: |-
          echo "Service URL: ${{ steps.deploy.outputs.url }}"
